apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-java-app
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-java-app
  template:
    metadata:
      labels:
        app: simple-java-app
    spec:
      containers:
      - name: simple-java-app
        image: 149215380122.dkr.ecr.us-east-1.amazonaws.com/helloworld/helloworldweb:latest
        ports:
        - containerPort: 8080
